#%RAML 1.0
title: Simplified Check-In PAPI
version: v1
baseUri: https://tngaa-check-in-papi-uniqid.shard.usa-e1.cloudhub.io/api/v1
description: Check-In PAPI allows you to check-in to an AnyAirline flight and check-in any additional baggage by providing a PNR(Passenger Name Record) and last name, paying for any baggage using Paypal.

types:
  Checkin:
    description: Represents a check-in request for a given passenger.
    type: object
    properties:
      lastName: string
      numBags: integer
    example:
      lastName: "Smith"
      numBags: 2
  PaymentId:
    description: Represents an instance of a Payment made.
    properties:
      paymentID: string
    example: 
      paymentID: "PAY-1AKD7482FAB9STATKO"
  PaymentApproval:
    description: Represents an approved Payment linked to the Payment requested and the Payer that made the payment by ID.
    properties:
      paymentID: string
      payerID: string
    example:
      paymentID: "PAY-1AKD7482FAB9STATKO"
      payerID: "STK829AJDK9"
  BoardingPass: 
    description: Represents a Boarding Pass for a Passenger linked via PNR(Passenger Name Record).
    properties:
      lastName: string
      flightDate:
        description: flight date in local time according to the departing airport 
        type: date-only
      depart: 
        description: flight departure time in local time according to the departing airport
        type: time-only
      boarding:
        description: boarding time in local time according to the departing airport 
        type: time-only
      gate: string
      flight: string
      airportDepart: string
      airportArrive: string
      class:
        enum: [First, Premium, Business, Economy]
        type: string
      seat: string
      bagsCount: number
      PNR: string
    example:
      lastName: "Smith"
      flightDate: "2019-02-14"
      depart: "14:30:00"
      boarding: "13:15:00"
      gate: "4A"
      flight: "ANY6584"
      airportDepart: "ATL"
      airportArrive: "SFO"
      class: "Economy"
      seat: "16C"
      bagsCount: 2
      PNR: "928382J"

/tickets/{PNR}:
  /checkin:
    description: Checks the passenger in with given number of bags
    put:
      body:
        application/json:
          type: Checkin
      responses:
        200:
          description: If there is baggage to check in, return a payment ID from the Paypal SAPI for the passenger to approve payment. Payment approval happens in the Mobile App. If there is no baggage to check in, return the boarding pass.
          body:
            application/json:
              type: PaymentId | BoardingPass
              examples:
                withBags:
                  paymentID: "PAY-1AKD7482FAB9STATKO"
                withoutBags:
                  lastName: "Smith"
                  flightDate: "2019-02-14"
                  depart: "14:30:00"
                  boarding: "13:15:00"
                  gate: "4A"
                  flight: "ANY6584"
                  airportDepart: "ATL"
                  airportArrive: "SFO"
                  class: "Economy"
                  seat: "16C"
                  bagsCount: 0
                  PNR: "928382J"
        400:
          body:
            application/json:
              example: |
                {"message": "Invalid passenger name record or bad data uploaded."}
  /paymentApproval:
    description: Execute payment after passenger's approval from the Mobile App.
    put:
      body:
        application/json:
          type: PaymentApproval
      responses:
        200:
          body:
            application/json:
              type: BoardingPass
        400:
          body:
            application/json:
              example: |
                {"message": "Invalid passenger name record or bad data uploaded."}
        403:
          body:
            application/json:
              example: |
                {"message": "Invalid paymentId and payerId combination given. Cannot approve payment."}
